services:
  backend:
    image: adeelarshad01/mern-backend:latest
    container_name: backend
    restart: unless-stopped

    env_file:
      - ./server/.env

    ports:
      - "5050:5050"

    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  frontend:
    image: adeelarshad01/mern-frontend:latest
    container_name: frontend

    restart: unless-stopped

    ports:
      - "80:80"
    env_file:
      - ./client/.env

    depends_on:
      - backend

volumes:
  mongodb_data: